### ISSUE TITLE
PHP 8.0 support?

### ISSUE THREAD

**Issue by yanlep** [loevgaard/SyliusBrandPlugin#203]
Hello, is there anything in your plugin that can't works with PHP 8.0 ?
I would like to do a "composer require loevgaard/sylius-brand-plugin" on a fresh Sylius install, using PHP 8.0 and composer tell me the PHP requirement is incompatible (php: ^7.2).

On another already installed version (done with PHP 7.4) I switched my server to PHP 8.0 and your plugin seems to still working.
Perhaps you could update your composer.json to set you require with: "php": "^7.2 || ^8.0"?

**Comment by loevgaard** [comment]
Hi, @yanlep 

Could you make a PR? :)

**Comment by yanlep** [comment]
> Could you make a PR? :)

Hello, I'm not sure what you would like I do...(I'm not English native)
A PR is a Pull Request, right? I never did that yet. I have to understand how it works...

**Comment by yanlep** [comment]
Hello, I didn't had the time to do a PR but it seems someone did: https://github.com/loevgaard/SyliusBrandPlugin/pull/204
Is it ok like this? Will you validate and update your plugin?
