### ISSUE TITLE
for sylius 1.11

### ISSUE THREAD

**Issue by Olivier127** [loevgaard/SyliusBrandPlugin#206]
Add parameters 

```
parameters:
  loevgaard_sylius_brand.model.brand.class: Loevgaard\SyliusBrandPlugin\Model\Brand
  loevgaard_sylius_brand.model.brand_image.class: Loevgaard\SyliusBrandPlugin\Model\BrandImage
```

to loevgaard_sylius_brand.yaml

**Comment by Roshyo** [comment]
Hi @Olivier127 Could you elaborate on why would that be needed? I'm afraid I don't understand.

**Comment by remylrt** [comment]
Hi @Roshyo,
I tried to install the plugin in my Sylius 1.11 project but Symfony was unable to resolve Brand and BrandImage classes paths.
![image](https://user-images.githubusercontent.com/45857737/189878258-06e92a0f-5acd-4624-8346-221b08e3bb74.png)
Olivier's code solves the problem :)

**Comment by loevgaard** [comment]
That's because the plugin class should be added _above_ the grid bundle class in bundles.php :)
