### ISSUE TITLE
Add brand fixture

### ISSUE THREAD

**Issue by Prometee** [loevgaard/SyliusBrandPlugin#28]
I think this is an important feature to add, if you want to deploy a shop and don't want to export your dev database to your prod one, you will need fixtures to quickly add required data to your shop.

If I have enough time I will make a PR with necessary tests like I do it on [SyliusInvoicingPlugin](https://github.com/Sylius/InvoicingPlugin/pull/74)

**Comment by loevgaard** [comment]
Sounds great :)
