### ISSUE TITLE
[UI] Use name instead of code in breadcrumbs

### ISSUE THREAD

**Issue by loevgaard** [loevgaard/SyliusBrandPlugin#40]
![image](https://user-images.githubusercontent.com/2412177/54186467-c5321180-44ab-11e9-8aed-7130a5228558.png)

**Comment by igormukhingmailcom** [comment]
I would like to suggest leave it as is as its default approach Sylius using (it uses `resource.code|default(resource.id)` at breadcrumb item that represents some particular resource).

Why this is good approach from my POV - some different products can have same names but different codes as its unique field. And its better to have unique data in breadcrumb for better identification (at screenshots, etc).

WDYT?

**Comment by loevgaard** [comment]
Let's keep it like that then :)
