### ISSUE TITLE
Installation incomplete on sylius 1.4.2

### ISSUE THREAD

**Issue by mathieudureisseix** [loevgaard/SyliusBrandPlugin#50]
Hi !
I ve just installed the plugin on Sylius 1.4.2 and there are missing directory on loevgaard/sylius-brand-plugin like Doctrine.
i need help to complete the setup.
Best regards
Mathieu

**Comment by igormukhingmailcom** [comment]
Hi, @mathieudureisseix.

What exactly directory missing (write path related to your app root)?

**Comment by mathieudureisseix** [comment]
Hi @igormukhingmailcom ,
thanks for your reply.
In fact there are missing directories in vendor loevgaard. Like Entity, Doctrine.
I had to fixed it manualy. It works now. 
Best regards
Mathieu
