### ISSUE TITLE
Brand description

### ISSUE THREAD

**Issue by Simas06** [loevgaard/SyliusBrandPlugin#54]
Hey, started using the plugin and thought it would be nice to have brand description field, so it would be easily accessible on product page to display.

How I could extend the Brand entity to add description field ?
Or is it worth considering to add to plugin itself ?

**Comment by loevgaard** [comment]
Hi @Simas06 

Glad you started using the plugin :)

Regarding the description - we will consider it. It's not a bad idea :)

But for now you can see how to extend/customize models here: https://docs.sylius.com/en/1.5/customization/model.html
