### ISSUE TITLE
Missing default template for Shop/show.html.twig

### ISSUE THREAD

**Issue by JaisDK** [loevgaard/SyliusBrandPlugin#71]
Navigating to /brand/{code} as defined in src/Resources/config/routing/shop.yaml yields an error Unable to find template "/show.html.twig"

This means it's looking for the template in the root of the templates folder instead of the brand bundle tempalte folder. To fix this you have to add the entire route definition in your own project instead of just being able to overwrite the template file.

**Comment by loevgaard** [comment]
Hi @JaisDK 

Can you provide a PR to fix it? :)
